# Generated by Django 4.1 on 2022-08-13 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_userid_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='userId',
            new_name='user_id',
        ),
    ]
